### ISSUE TITLE
Unable to create a peer 'out of the box'

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#56] opened 2024-06-03 19:49 UTC
With the default stuff, after tweaking server config, I'm unable to add a peer with no proper explanation why
![image](https://github.com/vijaygill/wg-ui-plus/assets/4427990/37b386d1-d86b-411e-950c-23ad9ed2eedd)

**Comment by vijaygill** [comment] 2024-06-03 20:25
@thecoshman - Cannot reproduce it here.
May be the permissions on the data folder on the host side?
Rememeber the application runs under non-root user. But when docker container starts and if mounted volumes folders are created, those are created as root (docker feature/bug/issue/whatever). This is why I have suggested "mkdir ./data" in the usage section of the readme. dod you create the folder manually before using docker compose?

**Comment by vijaygill** [comment] 2024-06-05 17:49
@thecoshman I presume your permissions issue is sorted. Can this ticket be closed?

**Comment by thecoshman** [comment] 2024-06-05 17:57
Not yet, but I'm also trying to test things via compose. Going to circle back to just running the container directly to test things out first

**Comment by vijaygill** [comment] 2024-06-05 17:59
> Not yet, but I'm also trying to test things via compose. Going to circle back to just running the container directly to test things out first

It will be great if you could please first follow the instructions in the README and then later migrate your setup to use compose. This will help in testing out those instructions too.

**Comment by vijaygill** [comment] 2024-06-06 17:36
@thecoshman closing this ticket. Reopen if you still have this issue.

**Closed by vijaygill** 2024-06-06 17:36 UTC
